# Generated by Django 3.2 on 2021-04-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='users/pictures'),
        ),
    ]
