# Generated by Django 3.2 on 2021-05-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('A', 'Administrador'), ('U', 'Usuario')], default='A', max_length=1),
        ),
    ]
