# Generated by Django 3.2.2 on 2021-05-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boletoAerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('vuelo', models.PositiveSmallIntegerField()),
                ('srcClss1', models.PositiveSmallIntegerField()),
                ('srcClss2', models.PositiveSmallIntegerField()),
                ('srcClss3', models.PositiveSmallIntegerField()),
                ('subTotal', models.FloatField()),
                ('descuento', models.FloatField()),
                ('total', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
