# Generated by Django 3.2 on 2021-05-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletoaerolinea',
            name='modified',
        ),
    ]
